services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: abir
      POSTGRES_PASSWORD: SECRET
      POSTGRES_DB: defaultdb
      PGDATA: /data/postgres
    volumes:
      - /home/abir/database_data/postgresql/data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - keybase-net
    restart: unless-stopped

  backend:
    container_name: keybase-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: keybase
      POSTGRES_PASSWORD: SECRET
      POSTGRES_DB: keybase
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # Use internel postgres or not - default true as this dockerfiles provides one. If you have your own postgre server always running then set to false and update the DATABASE_URL accordingly
      USE_INTERNAL_POSTGRES: "true"
      DATABASE_URL: postgresql+psycopg2://keybase:SECRET@postgres:5432/keybase
    ports:
      - "8000:8000"
    networks:
      - keybase-net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    container_name: keybase-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3000:3000"
    networks:
      - keybase-net
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m

networks:
  keybase-net:
    driver: bridge
